### ISSUE TITLE
what's the best way to return results of an R script with deployR?

### ISSUE THREAD

**Issue by dfalbel** [Microsoft/deployrUtils#14]
I'm writing an R Script to be used in deployR.

For example my script could be something like this:

```
deployrInput('{"name": "x", "render": "integer", "default": 6}')
deployrInput('{"name": "y", "render": "integer", "default": 6}')
results <- x*y
results
```

I wan't my call to the API to return the `results` object.
The best way is to catch the `results` object with the call?

```
deployr.io('/r/repository/script/execute')   
   .data({ filename: 'filename.R', author: 'daniel'})
   .numeric('x', 6)
   .numeric('y', 5)
   .routput('results')
   .end(function(res) {
     a = res.deployr.response.workspace.objects[0];
     console.log(a.value);
});
```

 I don't like this way because I will always have to tell the application developpers which is the value they have to catch from my script.

I would like to be able to just return a value that could be acessed with `res.deployr.response.value`, or any standard way..

**Comment by swells** [comment]
Hello,

All `routput` results end up in the `workspace` property of the JSON markup response as you know. The results can be 0 or more, hence you have to know the `name` of what to pluck out. With that said, we do have a "helper" that is attached to the response `res` in the callback named `.workspace()`:
-  Return the entire workspace, which is an `Array` of object literals:

``` js
var ws = res.workspace(); // Array
```
- Return a specific `routput` item as an object-literal by name in the workspace `Array`:

``` js
var results = res.workspace('results');  // object
```

Lets take your example:

```
deployr.io('/r/repository/script/execute')   
   .data({ filename: 'filename.R', author: 'daniel'})
   .numeric('x', 6)
   .numeric('y', 5)
   .routput('results')
   .end(function(res) {
      // where `results` === name of your `routput` defined above
      var results = res.workspace('results').value;
});
```

In addition to `.workspace()` there is also a "helper" called `.get('property')` for more generic property retrieval. For example:

``` js
.end(function(res) {
   var console = res.get('console');
});
```

These helpers make things less verbose in having to march down the response like so: `res.deployr.response.workspace.objects[0]` which is ugly I agree.

> I would like to be able to just return a value that could be acessed with res.deployr.response.value, or any standard way..

With all that said, the current implementation requires you to at least know the name of the `routput` because it could be 0 or more (which one would you expect?) for example:

``` js
deployr.script('/danile/root/filename.R')   
   .numeric('x', 6)
   .numeric('y', 5)
   .routput('result1')
   .routput('result2')
   .routputs( ['result3', 'result4', 'result5'] )
   .end(function(res) {
      var ws = res.workspace;

      var result1 = ws('result1').value;
      var result2 = ws('result2').value;
      var result3 = ws('result3').value;
      var result4 = ws('result4').value;
      var result5 = ws('result5').value;
});
```

``` R
deployrInput('{"name": "x", "render": "integer", "default": 6}')
deployrInput('{"name": "y", "render": "integer", "default": 6}')
result1 <- x*y
result2 <- 'Hello'
result3 <- "JavaScript"
result4 <- 5 * 10
result5 <- "foldLeft"
```

**Comment by dfalbel** [comment]
Thanks very much for your answer.

You are right, I was not thinking of multiple outputs like this. I thought that if I needed multiple outputs I should return a list. But that's great!

I was not aware of theese "helpers" too, thank you very much for the tip!
