### ISSUE TITLE
deployrInput ignores existing variable value if default value is provided

### ISSUE THREAD

**Issue by warmdev** [Microsoft/deployrUtils#6]
Current code in  `deployrInput.R` line 100 only uses the existing value when it exists AND default value is not provided. As a result, script is unable to get input value from API request when a default value is provided in `deployrInput` declaration.

``` r
# if "name" variable exists, use it instead of default
  if (!is.null(name)) {
    if (exists(name) && is.null(default)) {
      x <- get(name)  
    } else if (exists(name)) {
      return
    } 
  }
```

**Comment by swells** [comment]
Thanks. We are aware of this and will be pushing out a patch ASAP.

**Comment by Orbifold** [comment]
ASAP is relative...[posted the issue on 28th last month](https://groups.google.com/forum/#!topic/deployr/3UBLuO_AURg) and still waiting for it. If our stuff would be in production, I'd have lost my job meanwhile. 
I mean, it would be good if you'd push this a bit.

**Comment by swells** [comment]
A little more complicate than that.  We unfortunately need to bundle this package with the server and go through those distribution channels, ect... We aim to have a build by EOD.

Bundling packages is a big problem like this. We are waiting to get it on CRAN which would make this easier however there are internal constraints that prevent us from doing so.

Thanks for the patience. As always PR are welcome.

**Comment by swells** [comment]
Just an update on this. A hot fix branch `hotfix-v1.0.1` has been created with the fix for this and merged back in. I will release it as a 'pre-release/RC1` as soon as I can (waiting on the windows version) with the accompanying built package source as to not continue to block folks in the immediate:
- Linux:  `deployrUtils_1.0.1.tar.gz`  
- Windows:  `deployrUtils_1.0.1.zip`  

I will also supply directions on how to install it both on DeployR Windows/Linux. 

Once we get a DeployR server build and bundled with this patch I will mark it as an official release (more on this when I post the release notes).

Thanks for your patience.

**Comment by swells** [comment]
Hello, I just pushed a [pre-release](https://github.com/deployr/deployrUtils/releases/tag/v1.0.1-rc1) which address this issue. There are instruction in the release notes which detail how to install it.

Once we get a DeployR server build and bundled with this patch I will mark it as an official release and close. I do not expect anything to change here in `deployrUtils` between now and then.

Please raise an issue if you are still seeing problems.

**Comment by Orbifold** [comment]
Just installed it on Win2008 and, alleluia, the deployrInput works as should now. Thank you for making this pre-release available, made my day.

**Comment by swells** [comment]
Resolved. Now [Closing](https://github.com/deployr/deployrUtils/commit/6cbcd0a7942d568cfad18fe0e945f862c2b9aa33), see comments.
